name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [master]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        check-latest: true
    - run: npm install
    - run: npm run build --if-present
    - run: npm test

    - name: Build the Docker image
      run: |
        echo ${{ secrets.ALIYUN_PASSWORD }} | docker login --username=${{ secrets.ALIYUN_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=stdin
        docker build -t koa-actions:latest .
        docker tag koa-actions registry.cn-hangzhou.aliyuncs.com/aaronwb/koa-actions:latest
        docker push registry.cn-hangzhou.aliyuncs.com/aaronwb/koa-actions:latest
    - run: echo "Push Docker Image success"

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name:       ${{ github.ref }}
        release_name:   Release ${{ github.ref }}
#        body: |

        draft: false
        prerelease: false
